# Available themes:
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
# https://pages-themes.github.io/leap-day/
theme: jekyll-theme-dinky

title: NeoJAL Github page!
description: Taking notes...
